SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

INSERT INTO `tblProduct` (`prodId`, `prodName`, `prodDescription`, `prodStock`, `prodPrice`, `prodMeshName`) VALUES
(1, 'Apple', 'This is just a fuckin'' apple', 1, 1, 'Apple.obj'),
(2, 'Banana', 'Just for scale', 2, 2, 'BananaGroup.obj'),
(3, 'BlueMilk', 'Milk for Smurfs', 1, 1, 'BlueMilk.obj'),
(4, 'BrownEgg', 'Take that', 1, 1, 'BrownEgg.obj'),
(5, 'CaramelDoughnut', 'Homer lifestyle', 1, 1, 'CaramelDoughnut.obj'),
(6, 'Carrot', 'Donkey motivation', 1, 1, 'Carrot.obj'),
(7, 'Chocolate', 'Always good to eat', 1, 1, 'Chocolate.obj'),
(8, 'ChocolateDoughnut', 'Two good things in one', 1, 1, 'ChocolateDoughnut.obj'),
(9, 'Emmental', 'When French people try to make cheese', 1, 1, 'Emmental.obj'),
(10, 'Fish', '100% fresh guaranteed', 1, 1, 'Fish.obj'),
(11, 'GreenMilk', 'Milk for Hulk', 1, 1, 'GreenMilk.obj'),
(12, 'Gruyere', 'Real cheese', 1, 1, 'Gruyere.obj'),
(13, 'Ham', 'No pig inside ... lol just kidding', 1, 1, 'Ham.obj'),
(14, 'JamDoughnut', 'Jam it boy, JAM IT', 1, 1, 'JamDoughnut.obj'),
(15, 'Lolipop', '+18', 1, 1, 'Lolipop.obj'),
(16, 'PaperTowel', 'Clean your hands', 1, 1, 'PaperTowel.obj'),
(17, 'Pepper', 'For people who don''t like food', 1, 1, 'Pepper.obj'),
(18, 'Pumpkin', 'For sale between 15 oct and 31 oct', 1, 1, 'Pumpkin.obj'),
(19, 'RedMilk', 'Milk for Rednecks', 1, 1, 'RedMilk.obj'),
(20, 'Scotch', 'You can fix it with this', 1, 1, 'Scotch.obj'),
(21, 'Steak', 'For everyday use', 1, 1, 'Steak.obj'),
(22, 'Toblerone', 'Swiss chocolate for tourists', 1, 1, 'Toblerone.obj'),
(23, 'ToiletPaper', 'Second thing most essential, first is your mom', 1, 1, 'ToiletPaper.obj'),
(24, 'WhiteEgg', 'KKK egg', 1, 1, 'WhiteEgg.obj'),
(25, 'YoghurtApple', 'Apple and yoghurt', 1, 1, 'YoghurtApple.obj'),
(26, 'YoghurtNature', 'Nature and yoghurt', 1, 1, 'YoghurtNature.obj'),
(27, 'YoghurtStrawberry', 'Straw and berry and yoghurt', 1, 1, 'YoghurtStrawberry.obj'),
(28, 'YoghurtVanilla', 'Vanilla Ice yoghurt', 1, 1, 'YoghurtVanilla.obj');