-- MySQL Script generated by MySQL Workbench
-- Wed 24 Feb 2016 10:23:20 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_test` DEFAULT CHARACTER SET utf8 ;
USE `shop_test` ;

-- -----------------------------------------------------
-- Table `shop_test`.`tblCustomer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`tblCustomer` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`tblCustomer` (
  `cusId` INT NOT NULL AUTO_INCREMENT,
  `cusFirstName` VARCHAR(50) NULL,
  `cusLastName` VARCHAR(50) NULL,
  `cusGender` ENUM('M', 'F') NULL,
  `cusEmail` VARCHAR(100) NULL,
  `cusPhone` VARCHAR(15) NULL,
  PRIMARY KEY (`cusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_test`.`tblAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`tblAddress` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`tblAddress` (
  `addrId` INT NOT NULL AUTO_INCREMENT,
  `addrStreet` VARCHAR(40) NULL,
  `addrCity` VARCHAR(20) NULL,
  `addrZip` VARCHAR(5) NULL,
  PRIMARY KEY (`addrId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_test`.`linkCustomerAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`linkCustomerAddress` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`linkCustomerAddress` (
  `linkCusId` INT NOT NULL,
  `linkAddrId` INT NOT NULL,
  PRIMARY KEY (`linkCusId`, `linkAddrId`),
  INDEX `addrId_idx` (`linkAddrId` ASC),
  CONSTRAINT `cusId`
    FOREIGN KEY (`linkCusId`)
    REFERENCES `shop_test`.`tblCustomer` (`cusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addrId`
    FOREIGN KEY (`linkAddrId`)
    REFERENCES `shop_test`.`tblAddress` (`addrId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_test`.`tblOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`tblOrder` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`tblOrder` (
  `ordId` INT NOT NULL AUTO_INCREMENT,
  `ordCusId` INT NULL,
  `ordAddrId` INT NULL,
  `ordDate` DATETIME NULL,
  `ordStatus` INT NULL,
  PRIMARY KEY (`ordId`),
  INDEX `cusId_idx` (`ordCusId` ASC),
  INDEX `addrId_idx` (`ordAddrId` ASC),
  CONSTRAINT `cusId`
    FOREIGN KEY (`ordCusId`)
    REFERENCES `shop_test`.`tblCustomer` (`cusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addrId`
    FOREIGN KEY (`ordAddrId`)
    REFERENCES `shop_test`.`tblAddress` (`addrId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_test`.`tblProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`tblProduct` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`tblProduct` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `prodName` VARCHAR(30) NULL,
  `prodDescription` VARCHAR(255) NULL,
  `prodStock` INT NULL,
  `prodPrice` FLOAT NULL,
  `prodMeshName` VARCHAR(50) NULL,
  PRIMARY KEY (`prodId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_test`.`linkOrderProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_test`.`linkOrderProduct` ;

CREATE TABLE IF NOT EXISTS `shop_test`.`linkOrderProduct` (
  `linkOrdId` INT NOT NULL,
  `linkProdId` INT NOT NULL,
  `linkQuantity` INT NULL,
  `linkProductPrice` FLOAT NULL,
  PRIMARY KEY (`linkOrdId`, `linkProdId`),
  INDEX `prodId_idx` (`linkProdId` ASC),
  CONSTRAINT `ordId`
    FOREIGN KEY (`linkOrdId`)
    REFERENCES `shop_test`.`tblOrder` (`ordId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prodId`
    FOREIGN KEY (`linkProdId`)
    REFERENCES `shop_test`.`tblProduct` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
